default_platform(:ios)

platform :ios do
  desc "Pull Request açıldığında unit testleri çalıştırır"
  lane :ci_tests do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "60"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"

    root_path = sh("git rev-parse --show-toplevel", print_command: false).strip
    Dir.chdir(root_path)

    sh "pwd"
    sh "ls -la"
    sh "find . -name '*.xcodeproj'"

    project_path = Dir.glob("*.xcodeproj").first
    UI.user_error!("❌ Xcode project not found!") if project_path.nil?

    puts "✅ Xcode project found at: #{project_path}"

    # Swift Package Manager bağımlılıklarını çöz
    sh "xcodebuild -resolvePackageDependencies -scheme fastlanesample -project #{project_path}"

   available_simulators = sh("xcrun simctl list devices available", print_command: false)
matched_simulator = available_simulators.match(/(iPhone\s15).*?\((.*?)\)/)

if matched_simulator.nil?
  UI.user_error!("❌ No available iPhone 15 simulator found!")
end

simulator_udid = matched_simulator[2]
puts "✅ Using simulator with UDID: #{simulator_udid}"

scan(
  scheme: "fastlanesample",
  clean: true,
  project: File.expand_path(project_path),
  derived_data_path: "./fastlane/derivedData",
  destination: "platform=iOS Simulator,OS=17.2,name=iPhone 15"
)
end

  desc "Develop branch'ine pushlandığında Firebase'e deploy eder"
  lane :deploy_to_firebase do
    build_app(
      scheme: "fastlanesample",
      export_method: "development"
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: ENV["FIREBASE_TESTERS"],
      groups: ENV["FIREBASE_GROUPS"],
      release_notes: "Yeni build develop branch'inden gönderildi!"
    )
  end

  desc "Main branch'ine pushlandığında TestFlight'a gönderir"
  lane :deploy_to_testflight do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_API_KEY"],
      in_house: false
    )

    build_app(
      scheme: "fastlanesample",
      export_method: "app-store"
    )
    
    upload_to_testflight
  end
end