default_platform(:ios)

platform :ios do
  desc "Pull Request açıldığında unit testleri çalıştırır"
  lane :ci_tests do
    scan(
      scheme: "fastlanesample",
      clean: true,
      destination: "platform=iOS Simulator,id=71D594E0-3E1E-4C31-AFB9-DFEE3E99586F"
    )
  end

  desc "Develop branch'ine pushlandığında Firebase'e deploy eder"
  lane :deploy_to_firebase do
    build_app(
      scheme: "fastlanesample",
      export_method: "development"
    )
    
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: ENV["FIREBASE_TESTERS"], # Tek tek e-posta adresleri
      groups: ENV["FIREBASE_GROUPS"],   # Eğer grup kullanıyorsan
      release_notes: "Yeni build develop branch'inden gönderildi!"
    )
  end

  desc "Main branch'ine pushlandığında TestFlight'a gönderir"
  lane :deploy_to_testflight do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],       # API Key ID
      issuer_id: ENV["APP_STORE_ISSUER_ID"], # Apple Issuer ID
      key_content: ENV["APP_STORE_API_KEY"], # Base64 kodlanmış API Key içeriği
      in_house: false
    )

    build_app(
      scheme: "fastlanesample",
      export_method: "app-store"
    )
    
    upload_to_testflight
  end
end