name: iOS CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install Bundler
        run: gem install bundler
      - name: Install Fastlane
        run: bundle install
      - name: Run Unit Tests
        run: fastlane run_tests

  deploy:
    name: Deploy
    needs: tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install Bundler
        run: gem install bundler
      - name: Install Fastlane
        run: bundle install

      - name: Decode App Store API Key
        run: echo "${{ secrets.APP_STORE_API_KEY }}" | base64 --decode > AuthKey.p8

      - name: Deploy to Firebase (Develop)
        if: github.ref == 'refs/heads/develop'
        run: fastlane deploy_to_firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TESTERS: ${{ secrets.FIREBASE_TESTERS }}
          FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}

      - name: Deploy to TestFlight (Main)
        if: github.ref == 'refs/heads/main'
        run: fastlane deploy_to_testflight
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_API_KEY: AuthKey.p8
